export const timeline = [
  {
    year: "2024",
    title: "Software Engineer",
    company: "PayRetailers",
    logoUrl: "/assets/resume/payretailers-logo.png",
    consultingCompany: null,
    consultingCompanyLogoUrl: null,
    companyUrl: "https://www.payretailers.com/",
    description:
      "Focused on .NET Core, EF, and React, I advanced in software development with DDD and CQRS, optimizing backend solutions. Utilized continuous deployment, enhanced security via OAuth, and applied MediatR for command-query separation, embodying best practices in clean code and architecture for efficient software delivery.",
    tags: [".NET Core", "CQRS", "DDD", "OAuth", "React", "Clean Code"],
  },
  {
    year: "2023",
    title: "Software Engineer",
    company: "InnoIT Consulting",
    logoUrl: "/assets/resume/innoit-logo.png",
    consultingCompany: null,
    consultingCompanyLogoUrl: null,
    companyUrl: "https://www.innoit.es/",
    description:
      "Worked on various projects utilizing .NET Core, Microservices, DDD, and Entity Framework. Focused on relational databases like SQL Server and SQLite, and employed GitHub Actions for CI/CD pipelines.",
    tags: [".NET Core", "Microservices", "Entity Framework", "SQL Server", "CI/CD", "DDD"],
  },
  {
    year: "2021",
    title: "Software Engineer",
    company: "Bonzzu",
    logoUrl: "/assets/resume/bonzzu-logo.png",
    consultingCompany: "Intelliflo – Invesco Ltd",
    consultingCompanyLogoUrl: "/assets/resume/intelliflo-logo.png",
    companyUrl: "https://www.bonzzu.com/",
    consultingCompanyUrl: "https://www.intelliflo.com/",
    description:
      "Collaborated on financial microservices, primarily for Intelliflo's key client, Invesco. Leveraged .NET Core, Entity Framework, SQL Server, Redis, GitHub Actions, and AWS infrastructure. Adopted SAFe methodologies and tools like Azure DevOps and Jira for agile workflows.",
    tags: [".NET Core", "Microservices", "AWS", "Redis", "SAFe", "SQL Server"],
  },
  {
    year: "2019",
    title: ".NET Software Developer",
    company: "NEORIS",
    logoUrl: "/assets/resume/neoris-logo.png",
    consultingCompany: "Stock Market Trading Rosario",
    consultingCompanyLogoUrl: "/assets/resume/stock-market-trading-logo.png",
    companyUrl: "https://www.neoris.com/",
    consultingCompanyUrl: "https://www.bcr.com.ar/",
    description:
      "Developed and maintained web and desktop applications with WPF, MVC, .NET Core, and Angular in WCF-based SOA architectures. Managed Extranet security using digital certificates and mitigated inconsistencies in rural lease contracts using Microsoft Workflow Foundation. Mentored students and graduates for their first jobs.",
    tags: [".NET Core", "WPF", "SOA", "Digital Certificates", "Mentorship"],
  },
  {
    year: "2019",
    title: ".NET Developer",
    company: "Tesis IT & Automation",
    logoUrl: "/assets/resume/tesis-logo.png",
    consultingCompany: "Cordial Financial Company",
    consultingCompanyLogoUrl: "/assets/resume/cordial-logo.png",
    companyUrl: "https://tesis.com.ar/",
    consultingCompanyUrl: "https://www.cordialfinanciera.com.ar/",
    description:
      "Maintained large-scale SOA applications and small accounting systems using VB6. Developed REST APIs with .NET Core and Angular. Worked on WCF web services and Java applications for call centers, alongside Oracle SQL management.",
    tags: [".NET Core", "REST APIs", "SOA", "VB6", "Oracle SQL"],
  },
  {
    year: "2018",
    title: "Software Developer",
    company: "Tecso",
    logoUrl: "/assets/resume/tecso-logo.png",
    consultingCompany: "Citibank Latin America",
    consultingCompanyLogoUrl: "/assets/resume/citi-logo.png",
    companyUrl: "https://www.tecso.coop/",
    consultingCompanyUrl: "https://www.citigroup.com/",
    description:
      "Frontend development and maintenance for Citibank's home banking systems using Java, Citi proprietary frameworks, and Oracle SQL for database management.",
    tags: ["Java", "Oracle SQL", "Frontend", "Banking"],
  },
  {
    year: "2015",
    title: "Software Developer",
    company: "Integral Pack Express S.A.",
    logoUrl: "/assets/resume/integral-pack-express-logo.png",
    consultingCompany: null,
    consultingCompanyLogoUrl: null,
    companyUrl: "https://www.integralpack.com.ar/",
    description:
      "Developed billing systems and corporate API integrations using ASP.NET MVC, C#, and PHP. Maintained internal systems for logistics and administrative purposes with MSSQL, MySQL, and SQLite.",
    tags: ["ASP.NET MVC", "C#", "PHP", "REST APIs", "MSSQL"],
  },
  {
    year: "2011",
    title: "Electronics Technical Maintenance",
    company: "Sacoa Entertainment",
    logoUrl: "/assets/resume/sacoa-logo.png",
    consultingCompany: null,
    consultingCompanyLogoUrl: null,
    companyUrl: "https://www.sacoa.com/",
    description:
      "Maintained electronics, including arcade machines, network wiring, and custom computers for entertainment parks. Provided customer support and resolved technical claims for hardware/software.",
    tags: ["Electronics", "Networking", "Arcade", "Customer Support"],
  },
  {
    year: "1992",
    title: "Birth Argentina",
    company: null,
    consultingCompany: "Italian",
    consultingCompanyLogoUrl: "/assets/resume/italy-logo.png",
    logoUrl: "/assets/resume/argentina-logo.png",
    description: "Born in Rosario, Santa Fe, Argentina. I’m Italian because my family’s originally from there—third generation, like most of Argentinians.",
    tags: ["Birth", "Argentinian", "Italian"],
  },
];

export const recommendations = [
  {
    name: "Jérôme GIRARD",
    position: "CEO at InnoIT Consulting",
    relation: "Jérôme managed Mauro directly",
    date: "October 14, 2024",
    profilePictureUrl: "https://media.licdn.com/dms/image/v2/C4E03AQGHBHHKJ6mjwA/profile-displayphoto-shrink_100_100/profile-displayphoto-shrink_100_100/0/1660561105074?e=1738800000&v=beta&t=EplQxglIAJUWpFkoGVe9iP44H9vC62vr40hOxG5sCFk",
    linkedInProfileUrl: "https://www.linkedin.com/in/girardjerome/",
    linkedInRecommendationUrl: "https://www.linkedin.com/in/maurogioberti/details/recommendations/?detailScreenTabIndex=0",
    translation: "Translated from Spanish",
    text: "I had the pleasure of meeting Mauro when we relocated him from Argentina to Spain to join our team at InnoIT. From the beginning, his strong expertise in .NET stood out, along with his exceptional soft skills. Mauro is a reliable professional with great technical abilities, always willing to share his knowledge and collaborate with the teams.",
  },
  {
    name: "Gina Marie Urizar (Passaretti)",
    position: "Life Organization Coach",
    relation: "Gina Marie was senior to Mauro but didn't manage Mauro directly",
    date: "February 23, 2024",
    profilePictureUrl: "https://media.licdn.com/dms/image/v2/D4D03AQEFQ3uvh_jb3A/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1698792726390?e=2147483647&v=beta&t=4FrBJ0I9-MMdVqjwutSE5e_dmcJf5f3STlzn_j3tNpI",
    linkedInProfileUrl: "https://www.linkedin.com/in/bellelumiere",
    linkedInRecommendationUrl: "https://www.linkedin.com/in/maurogioberti/details/recommendations/?detailScreenTabIndex=0",
    translation: null,
    text: "I highly recommend Mauro as a software developer, although he did not report directly to me. Mauro consistently demonstrated a remarkable level of professionalism and dedication while working with our client, Intelliflo. His excellent teamwork skills were evident as he consistently supported and encouraged his colleagues, fostering a positive and collaborative work environment. Mauro's commitment to continuous improvement was notable, as he actively sought to enhance both his technical expertise and soft skills, ultimately contributing to the overall success of our projects.",
  },
  {
    name: "Jay McMeans",
    position: "Head of Engineering (R&D) - Intelliflo",
    relation: "Jay Managed Mauro directly",
    date: "February 23, 2024",
    profilePictureUrl: "https://media.licdn.com/dms/image/v2/C4E03AQHPJdea0TlKPQ/profile-displayphoto-shrink_100_100/profile-displayphoto-shrink_100_100/0/1538140620016?e=1738800000&v=beta&t=_X70QaIiQc7mfWnz3EERfY9GJWvcRp42XHKaL6feghg",
    linkedInProfileUrl: "https://www.linkedin.com/in/jaymcmeans",
    linkedInRecommendationUrl: "https://www.linkedin.com/in/maurogioberti/details/recommendations/?detailScreenTabIndex=0",
    translation: null,
    text: "Mauro was a great asset on my team. He always had a great attitude and a willingness to jump in and get the job done. Mauro is a constant learner, and even if he is not knowledgeable in an area, he does what it takes to learn it. Mauro was not given permission by me to resign and move to another company. While he left a hole on one of my teams, he will nicely fill holes on another company's team.",
  },
  {
    name: "Gonzalo Racigh",
    position: "Project Leader - Scrum Master at TECSO Coop",
    relation: "Gonzalo worked with Mauro on the same team",
    date: "December 21, 2018",
    profilePictureUrl: "https://media.licdn.com/dms/image/v2/C4D03AQEB4A5GSVmsig/profile-displayphoto-shrink_100_100/profile-displayphoto-shrink_100_100/0/1660227384749?e=1738800000&v=beta&t=36WRV3NaxaQtVbIdDxXwQByfSPq8xrseTgApSHfpXeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/gonzaloracigh/",
    linkedInRecommendationUrl: "https://www.linkedin.com/in/maurogioberti/details/recommendations/?detailScreenTabIndex=0",
    translation: "Translated from Spanish",
    text: "Mauro is a professional with strong technical skills and knowledge of various development tools. He’s responsible and flexible, ready to take on all kinds of tasks. He’s proactive and always willing to help his teammates solve problems.",
  },
];